//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Areas.VuonThucVat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bo()
        {
            this.Hoes = new HashSet<Ho>();
        }
    
        public int ID { get; set; }
        public string TenBo { get; set; }
        public Nullable<int> PhanLop { get; set; }
    
        public virtual PhanLop PhanLop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ho> Hoes { get; set; }
    }
}
