//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Areas.VuonThucVat.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KHOADUOCEntities2 : DbContext
    {
        public KHOADUOCEntities2()
            : base("name=KHOADUOCEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bo> Boes { get; set; }
        public virtual DbSet<CayThucVat> CayThucVats { get; set; }
        public virtual DbSet<Chi> Chis { get; set; }
        public virtual DbSet<Ho> Hoes { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<Nganh> Nganhs { get; set; }
        public virtual DbSet<PhanLop> PhanLops { get; set; }
    }
}
