//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    using System.ComponentModel.DataAnnotations;

    public partial class CacCoSoLienKetDaoTao
    {
        public int MaCacCoSoLienKetDaoTao { get; set; }

        [Required(ErrorMessage = "Chýa nhâòp thông tin")]
        public string TenCacCoSoLienKetDaoTao { get; set; }

        [Required(ErrorMessage = "Chýa nhâòp thông tin")]
        public string NDTomTatCacCoSoLienKetDaoTao { get; set; }

        [Required(ErrorMessage = "Chýa nhâòp thông tin")]
=======
    
    public partial class CacCoSoLienKetDaoTao
    {
        public int MaCacCoSoLienKetDaoTao { get; set; }
        public string TenCacCoSoLienKetDaoTao { get; set; }
        public string NDTomTatCacCoSoLienKetDaoTao { get; set; }
>>>>>>> Minhtam
        public string NDChiTietCacCoSoLienKetDaoTao { get; set; }
    }
}
