//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiThucVat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiThucVat()
        {
            this.LoaiThucVats = new HashSet<LoaiThucVat>();
        }
    
        public int MaChiThucVat { get; set; }
        public string TenChiThucVat { get; set; }
        public int MaHoThucVat { get; set; }
    
        public virtual HoThucVat HoThucVat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiThucVat> LoaiThucVats { get; set; }
    }
}
