//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCTHH
    {
        public int ID { get; set; }
        public Nullable<int> ThucVat { get; set; }
        public Nullable<int> CongThucHoaHoc { get; set; }
    
        public virtual ThanhPhanHoaHoc ThanhPhanHoaHoc { get; set; }
        public virtual ThucVat ThucVat1 { get; set; }
    }
}
