//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThucVat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiThucVat()
        {
            this.ThucVats = new HashSet<ThucVat>();
        }
    
        public int MaLoaiThucVat { get; set; }
<<<<<<< HEAD
        public string TenLoaiThucVat { get; set; }
=======
        public string TenLoaiThucVatDau { get; set; }
        public string TenLoaiThucVatDuoi { get; set; }
>>>>>>> Minhtam
        public int MaChiThucVat { get; set; }
    
        public virtual ChiThucVat ChiThucVat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThucVat> ThucVats { get; set; }
    }
}
