//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LyLichKHCuaGV
    {
        public int MaLyLichKHCuaGV { get; set; }
        public string TenLyLichKHCuaGV { get; set; }
        public string NDTomTatLyLichKHCuaGV { get; set; }
        public string NDChiTietLyLichKHCuaGV { get; set; }
    }
}
