//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCKHVLUEntities : DbContext
    {
        public NCKHVLUEntities()
            : base("name=NCKHVLUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<BoThucVat> BoThucVats { get; set; }
        public virtual DbSet<CacBoMon> CacBoMons { get; set; }
        public virtual DbSet<CacCoSoLienKetDaoTao> CacCoSoLienKetDaoTaos { get; set; }
        public virtual DbSet<CacDeTaiDangNCCuaGV> CacDeTaiDangNCCuaGVs { get; set; }
        public virtual DbSet<CacDeTaiDangNCCuaSV> CacDeTaiDangNCCuaSVs { get; set; }
        public virtual DbSet<CacPhongThiNghiem> CacPhongThiNghiems { get; set; }
        public virtual DbSet<CauLacbo> CauLacboes { get; set; }
        public virtual DbSet<ChiThucVat> ChiThucVats { get; set; }
        public virtual DbSet<ChuongTrinhDaoTao> ChuongTrinhDaoTaos { get; set; }
        public virtual DbSet<CoCauToChuc> CoCauToChucs { get; set; }
        public virtual DbSet<DamBaoChatLuong> DamBaoChatLuongs { get; set; }
        public virtual DbSet<DaoTaoLienTucCPE> DaoTaoLienTucCPEs { get; set; }
        public virtual DbSet<DoanHoi> DoanHois { get; set; }
        public virtual DbSet<HoatDongNgoaiKhoa> HoatDongNgoaiKhoas { get; set; }
        public virtual DbSet<HoThucVat> HoThucVats { get; set; }
        public virtual DbSet<LoaiThucVat> LoaiThucVats { get; set; }
        public virtual DbSet<LopThucVat> LopThucVats { get; set; }
        public virtual DbSet<LyLichKHCuaGV> LyLichKHCuaGVs { get; set; }
        public virtual DbSet<NganhThucVat> NganhThucVats { get; set; }
        public virtual DbSet<PhanLopThucVat> PhanLopThucVats { get; set; }
        public virtual DbSet<QuyCheCongTacSV> QuyCheCongTacSVs { get; set; }
        public virtual DbSet<SOPDaoTao> SOPDaoTaos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiNguyen> TaiNguyens { get; set; }
        public virtual DbSet<TamNhinMTCL> TamNhinMTCLs { get; set; }
        public virtual DbSet<ThongTinNoiBo> ThongTinNoiBoes { get; set; }
        public virtual DbSet<ThucVat> ThucVats { get; set; }
        public virtual DbSet<TinTuc> TinTucs { get; set; }
        public virtual DbSet<TinTucSuKien> TinTucSuKiens { get; set; }
        public virtual DbSet<TuyenDung> TuyenDungs { get; set; }
    }
}
