//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOPDaoTao
    {
        public int MaSOPDaoTao { get; set; }
        public string TenSOPDaoTao { get; set; }
        public string NDTomTatSOPDaoTao { get; set; }
        public string NDChiTietSOPDaoTao { get; set; }
    }
}
