//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhPhanHoaHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhPhanHoaHoc()
        {
            this.ChiTietCTHHs = new HashSet<ChiTietCTHH>();
        }
    
        public int ID { get; set; }
        public string NhomChat { get; set; }
        public string CongThucHoaHoc { get; set; }
        public string TenDanhPhap { get; set; }
        public string CongThucPhanTu { get; set; }
        public string PubchemID { get; set; }
        public string TaiLieuThamKhao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCTHH> ChiTietCTHHs { get; set; }
    }
}
