//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucVat
    {
<<<<<<< HEAD
        public int MaCay { get; set; }
        public string TenVietNam { get; set; }
        public string TenKhoaHoc { get; set; }
        public string HoThucVat { get; set; }
        public string MoTa { get; set; }
        public string BoPhanDung { get; set; }
        public string ThanhPhanHoaHoc { get; set; }
        public string TacDungDuocLy { get; set; }
        public string LieuDung { get; set; }
        public string TaiLieuThamKhao { get; set; }
        public int MaLoaiThucVat { get; set; }
    
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucVat()
        {
            this.ChiTietCTHHs = new HashSet<ChiTietCTHH>();
        }
    
        public int MaCay { get; set; }
        public byte[] HinhAnh { get; set; }
        public string TenVietNam { get; set; }
        public string HoThucVat { get; set; }
        public string MoTa { get; set; }
        public string BoPhanDung { get; set; }
        public Nullable<int> SoLuongThanhPhanHoaHoc { get; set; }
        public string TacDungDuocLy { get; set; }
        public string LieuDung { get; set; }
        public string TaiLieuThamKhao { get; set; }
        public Nullable<int> MaLoaiThucVat { get; set; }
        public string TenKhac { get; set; }
        public string LinkMoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCTHH> ChiTietCTHHs { get; set; }
>>>>>>> Minhtam
        public virtual LoaiThucVat LoaiThucVat { get; set; }
    }
}
