//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021NCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucVat
    {
        public int MaCay { get; set; }
        public string TenVietNam { get; set; }
        public string TenKhoaHoc { get; set; }
        public string HoThucVat { get; set; }
        public string MoTa { get; set; }
        public string BoPhanDung { get; set; }
        public string ThanhPhanHoaHoc { get; set; }
        public string TacDungDuocLy { get; set; }
        public string LieuDung { get; set; }
        public string TaiLieuThamKhao { get; set; }
        public int MaLoaiThucVat { get; set; }
    
        public virtual LoaiThucVat LoaiThucVat { get; set; }
    }
}
